# Site settings
title: "CMS.S62"
full_name: "CMS.S62/S98 – Digital Humanities: Active Archives"
name: "Active Archives"
email: fendt@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the collaborative site for CMS.S62/S98, a Digital
  Humanities course at MIT taught by Kurt Fendt. Students will
  use this space to keep track of course resources, example
  projects, to post reading commentaries and design updates as
  their own design projects take shape. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cmss62.github.io" # the base hostname & protocol for your site
twitter_username: MIThyperstudio
github_username:  cmsS62
permalink: none

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: "http://cmss62.github.io/"
  relativeLinks: 'http://cmss62.github.io/links.jsonp'
  media: 'assets'
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          placeholder: "your name, or your team's name"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          options:
            - name: "Reading Commentary"
              value: "commentary"
            - name: "Project Ideas & Updates"
              value: "updates"
            - name: "Projects & Archives"
              value: "ext-projects"
            - name: "Data & Tools"
              value: "datasets"
            - name: "Bio"
              value: "people"
            - name: "Collaboration"
              value: "collaboration"
            - name: "Resources"
              value: "resources"
            - name: "About"
              value: "course"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Readings"
          placeholder: "Choose Reading(s)"
          options:
            - name: "Digital_Humanities"
              value: "Digital_Humanities"
            - name: "Archives"
              value: "Archives"
            - name: "Graphesis"
              value: "Graphesis"
            - name: "Cultural Heritage"
              value: "Cultural Heritage"
            - name: "Visualization"
              value: "Visualization"
            - name: "Storytelling"
              value: "Storytelling"
            - name: "Interface Design"
              value: "Interface Design"
            - name: "Activist Archives"
              value: "Activist Archives"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
